routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/mis-clinicas', 'HomeController@index')->middleware('verified')->name('panel-ppal');



Route::resource('clinicas', 'ClinicaController');

Route::middleware(['checkOwnership','auth'])->group(function () {

    Route::get('panel/clinica/{clinica_id}/', 'ClinicaController@panelClinica')->name('clinicas.panel');

    /******************* */
    
    Route::get('clinica/{clinica_id}/servicios'                                 ,'ServicioController@index'    )->name('servicios.index');
    Route::get('clinica/{clinica_id}/servicios/crear'                           ,'ServicioController@create'   )->name('servicios.create');
    Route::post('clinica/{clinica_id}/servicios/crear'                          ,'ServicioController@store'    )->name('servicios.store');
    Route::get('clinica/{clinica_id}/servicios/eliminar/{servicio_id}'          ,'ServicioController@destroy'  )->name('servicios.destroy');
    Route::get('clinica/{clinica_id}/servicios/ver/{servicio_id}'               ,'ServicioController@show'     )->name('servicios.show');
    Route::get('clinica/{clinica_id}/servicios/editar/{servicio_id}'            ,'ServicioController@edit'     )->name('servicios.edit');
    Route::patch('clinica/{clinica_id}/servicios/actualizar/{servicio_id}'      ,'ServicioController@update'   )->name('servicios.update');
    Route::delete('clinica/{clinica_id}/servicios/eliminar/{servicio_id}'       ,'ServicioController@destroy'  )->name('servicios.destroy');
    
    ///////////////////////////////////////

    Route::get('clinicas/{clinica_id}/propietarios'                   ,'propietarioController@index'    )->name('propietarios.index');
    Route::get('clinicas/{clinica_id}/propietarios/registrar'         ,'propietarioController@create'   )->name('propietarios.create');
    Route::post('clinicas/{clinica_id}/propietarios/registrar'        ,'propietarioController@store'    )->name('propietarios.store');
    Route::get('clinicas/{clinica_id}/propietarios/ver/{id}'          ,'propietarioController@show'     )->name('propietarios.show');
    Route::get('clinicas/{clinica_id}/propietarios/editar/{id}'       ,'propietarioController@edit'     )->name('propietarios.edit');
    Route::patch('clinicas/{clinica_id}/propietarios/editar/{id}'     ,'propietarioController@update'   )->name('propietarios.update');
    Route::delete('clinicas/{clinica_id}/propietarios/eliminar/{id}'  ,'propietarioController@destroy'  )->name('propietarios.destroy');

    /////////////////////////////////////////////////////////////////////////////////

    Route::get('clinicas/{clinica_id}/mascotas'                    ,'MascotaController@index'    )->name('mascotas.index');
    Route::get('clinicas/{clinica_id}/mascotas/registrar'          ,'MascotaController@create'   )->name('mascotas.create');
    Route::post('clinicas/{clinica_id}/mascotas/registrar'         ,'MascotaController@store'    )->name('mascotas.store');
    Route::get('clinicas/{clinica_id}/mascotas/ver/{id}'           ,'MascotaController@show'     )->name('mascotas.show');
    Route::get('clinicas/{clinica_id}/mascotas/editar/{id}'        ,'MascotaController@edit'     )->name('mascotas.edit');
    Route::patch('clinicas/{clinica_id}/mascotas/editar/{id}'      ,'MascotaController@update'   )->name('mascotas.update');
    Route::delete('clinicas/{clinica_id}/mascotas/eliminar/{id}'   ,'MascotaController@destroy'  )->name('mascotas.destroy');
});

Route::get('clinicas/{clinica_id}/Trabajadores','TrabajadoresController@index')->name('empleados.index');



Route::resource('especies','EspecieController')->middleware( 'role:god', 'auth' );



Route::resource('mascotas', 'MascotaController');

resources/views/partials/alert.blade.php
@include('flash::message')

@if( session()->has('alert') )

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-{{ session('alert') }}" role="alert">
            {!! session('msg') !!}
        </div>
    </div>
</div>
@endif


@if( $errors->any() )

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    </div>
</div>
@endif

resources/views/partials/topNav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">
                            <i class="fas fa-notes-medical"></i> Historias
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">
                            <i class="far fa-calendar-check"></i> Citas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">
                            <i class="fas fa-user-friends"></i> Propietarios
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">
                            <i class="fas fa-paw"></i> Animales
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <i class="fas fa-users-cog"></i> Hola, {{ Auth::user()->name }}! <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('clinicas.index') }}">
                                Clinicas
                            </a>
                            <a class="dropdown-item" href="#">
                                Empleados
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>