routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/mis-clinicas', 'HomeController@index')->middleware('verified')->name('panel-ppal');



Route::resource('clinicas', 'ClinicaController');

Route::middleware(['checkOwnership','auth'])->group(function () {

    Route::get('panel/clinica/{clinica_id}/', 'ClinicaController@panelClinica')->name('clinicas.panel');

    /******************* */
    
    Route::get('clinica/{clinica_id}/servicios'                                 ,'ServicioController@index'    )->name('servicios.index');
    Route::get('clinica/{clinica_id}/servicios/crear'                           ,'ServicioController@create'   )->name('servicios.create');
    Route::post('clinica/{clinica_id}/servicios/crear'                          ,'ServicioController@store'    )->name('servicios.store');
    Route::get('clinica/{clinica_id}/servicios/eliminar/{servicio_id}'          ,'ServicioController@destroy'  )->name('servicios.destroy');
    Route::get('clinica/{clinica_id}/servicios/ver/{servicio_id}'               ,'ServicioController@show'     )->name('servicios.show');
    Route::get('clinica/{clinica_id}/servicios/editar/{servicio_id}'            ,'ServicioController@edit'     )->name('servicios.edit');
    Route::patch('clinica/{clinica_id}/servicios/actualizar/{servicio_id}'      ,'ServicioController@update'   )->name('servicios.update');
    Route::delete('clinica/{clinica_id}/servicios/eliminar/{servicio_id}'       ,'ServicioController@destroy'  )->name('servicios.destroy');
    
    ///////////////////////////////////////

    Route::get('clinicas/{clinica_id}/propietarios'                   ,'propietarioController@index'    )->name('propietarios.index');
    Route::get('clinicas/{clinica_id}/propietarios/registrar'         ,'propietarioController@create'   )->name('propietarios.create');
    Route::post('clinicas/{clinica_id}/propietarios/registrar'        ,'propietarioController@store'    )->name('propietarios.store');
    Route::get('clinicas/{clinica_id}/propietarios/ver/{id}'          ,'propietarioController@show'     )->name('propietarios.show');
    Route::get('clinicas/{clinica_id}/propietarios/editar/{id}'       ,'propietarioController@edit'     )->name('propietarios.edit');
    Route::patch('clinicas/{clinica_id}/propietarios/editar/{id}'     ,'propietarioController@update'   )->name('propietarios.update');
    Route::delete('clinicas/{clinica_id}/propietarios/eliminar/{id}'  ,'propietarioController@destroy'  )->name('propietarios.destroy');

    /////////////////////////////////////////////////////////////////////////////////

    Route::get('clinicas/{clinica_id}/mascotas'                    ,'MascotaController@index'    )->name('mascotas.index');
    Route::get('clinicas/{clinica_id}/mascotas/registrar'          ,'MascotaController@create'   )->name('mascotas.create');
    Route::post('clinicas/{clinica_id}/mascotas/registrar'         ,'MascotaController@store'    )->name('mascotas.store');
    Route::get('clinicas/{clinica_id}/mascotas/ver/{id}'           ,'MascotaController@show'     )->name('mascotas.show');
    Route::get('clinicas/{clinica_id}/mascotas/editar/{id}'        ,'MascotaController@edit'     )->name('mascotas.edit');
    Route::patch('clinicas/{clinica_id}/mascotas/editar/{id}'      ,'MascotaController@update'   )->name('mascotas.update');
    Route::delete('clinicas/{clinica_id}/mascotas/eliminar/{id}'   ,'MascotaController@destroy'  )->name('mascotas.destroy');
});

Route::get('clinicas/{clinica_id}/Trabajadores','TrabajadoresController@index')->name('empleados.index');



Route::resource('especies','EspecieController')->middleware( 'role:god', 'auth' );



Route::resource('mascotas', 'MascotaController');

resources/views/especies/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Especie
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'especies.store']) !!}

                        @include('especies.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/especies/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Especie
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($especie, ['route' => ['especies.update', $especie->id], 'method' => 'patch']) !!}

                        @include('especies.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/especies/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control','maxlength' => 50,'minlength' => 3]) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::text('descripcion', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('especies.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/especies/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Especies</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('especies.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('especies.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/especies/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Especie
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('especies.show_fields')
                    <a href="{{ route('especies.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/especies/show_fields.blade.php
<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', 'Nombre:') !!}
    <p>{{ $especie->nombre }}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{{ $especie->descripcion }}</p>
</div>

resources/views/especies/table.blade.php
<div class="table-responsive">
    <table class="table" id="especies-table">
        <thead>
            <tr>
                <th>Nombre</th>
        <th>Descripcion</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($especies as $especie)
            <tr>
                <td>{{ $especie->nombre }}</td>
            <td>{{ $especie->descripcion }}</td>
                <td>
                    {!! Form::open(['route' => ['especies.destroy', $especie->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('especies.show', [$especie->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('especies.edit', [$especie->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>